services:
  mongo:
    image: mongo:7.0.7
    restart: unless-stopped
    command: ["--wiredTigerCacheSizeGB", "0.25"]
    volumes:
      - mongo_data:/data/db

  bot:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - "3000:3000"
    environment:
      - DISCORD_AZURE_BOOT_CONFIG_FILE=/app/config.json5
    volumes:
      - ./config.json5:/app/config.json5:ro

volumes:
  mongo_data: